### ISSUE TITLE
1.18.2 Startup error (Most likley because its made for 1.19)

### ISSUE THREAD

**Issue by TomLewis** [Dolphindalt/RetractableBridges#1]
Sorry all my servers are still on 1.18 until all plugins are updated by developers.
I still gave it a try on 1.18.2 and I got this error, no worries if its specific to 1.19 only and no backwards compatability I will just wait until im able to update to 1.19.

```
[13:38:54] [Server thread/INFO]: [RetractableBridges] Enabling RetractableBridges v0.0.1
[13:38:54] [Server thread/INFO]: [Minecraft.xyz.dcaron.bridges] [RetractableBridges] Plugin enabled.
[13:38:54] [Server thread/ERROR]: Error occurred while enabling RetractableBridges v0.0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pe" is null
	at java.util.ImmutableCollections$SetN.probe(ImmutableCollections.java:1007) ~[?:?]
	at java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:916) ~[?:?]
	at java.util.Set.of(Set.java:706) ~[?:?]
	at java.util.stream.Collectors.lambda$toUnmodifiableSet$9(Collectors.java:364) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[?:?]
	at xyz.dcaron.bridges.BridgeOptions.<init>(BridgeOptions.java:37) ~[RetractableBridges.jar:?]
	at xyz.dcaron.bridges.BridgesPlugin.readConfigurationFiles(BridgesPlugin.java:54) ~[RetractableBridges.jar:?]
	at xyz.dcaron.bridges.BridgesPlugin.onEnable(BridgesPlugin.java:43) ~[RetractableBridges.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:38:54] [Server thread/INFO]: [RetractableBridges] Disabling RetractableBridges v0.0.1
[13:38:54] [Server thread/INFO]: [Minecraft.xyz.dcaron.bridges] [RetractableBridges] Plugin disabled.
```

**Comment by Dolphindalt** [comment]
@TomLewis It could be an issue with the Java version. I will try to reproduce this. What version of Java are you running?

**Comment by TomLewis** [comment]
```
java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

**Comment by Dolphindalt** [comment]
@TomLewis  We happen to be running the same the exact same Java versions. I cannot get that error to reproduce itself. I did get a API version error, but this was expected as the plugin was designed for 1.19. I made a release for a 1.18.2 version. Can you try [this release](https://github.com/Dolphindalt/RetractableBridges/releases/tag/legacy) and see if you still get that strange error?

**Comment by TomLewis** [comment]
Gave it a try but similar error:
```
[15:08:10] [Server thread/INFO]: [RetractableBridges] Enabling RetractableBridges v1.0.0
[15:08:10] [Server thread/INFO]: [Minecraft.xyz.dcaron.bridges] [RetractableBridges] Plugin enabled.
[15:08:10] [Server thread/ERROR]: Error occurred while enabling RetractableBridges v1.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pe" is null
	at java.util.ImmutableCollections$SetN.probe(ImmutableCollections.java:1007) ~[?:?]
	at java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:916) ~[?:?]
	at java.util.Set.of(Set.java:706) ~[?:?]
	at java.util.stream.Collectors.lambda$toUnmodifiableSet$9(Collectors.java:364) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[?:?]
	at xyz.dcaron.bridges.BridgeOptions.<init>(BridgeOptions.java:37) ~[RetractableBridges-1.18.2.jar:?]
	at xyz.dcaron.bridges.BridgesPlugin.readConfigurationFiles(BridgesPlugin.java:54) ~[RetractableBridges-1.18.2.jar:?]
	at xyz.dcaron.bridges.BridgesPlugin.onEnable(BridgesPlugin.java:43) ~[RetractableBridges-1.18.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:08:10] [Server thread/INFO]: [RetractableBridges] Disabling RetractableBridges v1.0.0
```

I wonder if its because im using the last version of PurPur for 1.18.2?
https://purpurmc.org/downloads/1.18.2

**Comment by Dolphindalt** [comment]
@TomLewis Incredibly, I am able to reproduce this error when using that purpur jar. I had thought the issue was with purpur, but then I realized what the error was. In the configuration, there is a list of blocks that can be used as bridge materials. This list contains blocks exclusive to 1.19. The code that scans for these blocks is shown here:
```java
bridgeMaterials = configuration.getStringList("bridgeMaterials")
                .stream()
                .map(material -> Material.getMaterial(material))
                .collect(Collectors.toUnmodifiableSet());
```
The segment `Material.getMaterial(material)` takes a string from the config and converts it into some material. 1.19 blocks will be null and cause the NullPointerException to occur. To fix this, I have included some extra code.
```java
final Function<String, Material> warnForNullStringToMaterialFunc = (materialString) -> {
        final Material material = Material.getMaterial(materialString);
        if (material == null) {
            BridgesPlugin.log("Failed to parse block " + materialString + " from the configuration", Level.WARNING);
        }
        return material;
    };

    bridgeMaterials = configuration.getStringList("bridgeMaterials")
            .stream()
            .map(warnForNullStringToMaterialFunc)
            .filter(material -> material != null)
            .collect(Collectors.toUnmodifiableSet());
```
Now, blocks that do not load in 1.18 or blocks that have a spelling error in them are simply ignored and a warning is produced to the console in place of the error you are getting.
![2022-06-29-081600_1041x39_scrot](https://user-images.githubusercontent.com/13937320/176473077-2baa2884-3355-4e0d-829c-7f20400578c6.png)

I have put out a release for 1.18.2 and will make one for 1.19 that includes this bug fix. You can find the 1.18.2 patch [here](https://github.com/Dolphindalt/RetractableBridges/releases/tag/legacy-1.18.2-%231).

**Comment by TomLewis** [comment]
Thanks for the breakdown of the issue, its always good to learn something new!
The plugin now loads, but on first test found another bug, so I will make another ticket for that!
